// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi9uvFXcXhVHYhC1R4nqoNV_EgFqZB4ns',
    appId: '1:1062422767346:android:3789e37fb5f7d5d137926b',
    messagingSenderId: '1062422767346',
    projectId: 'e-baladya-2026',
    storageBucket: 'e-baladya-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
  apiKey: 'AIzaSyDD7KpBmfNSPREPRLWNQBrYCaqYBv5CISQ',
  appId: '1:1062422767346:ios:a18a989a1310264337926b',
  messagingSenderId: '1062422767346',
  projectId: 'e-baladya-2026',
  storageBucket: 'e-baladya-2026.firebasestorage.app',
  iosBundleId: 'com.eBaladya.eBaladya',
);

}