// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi9uvFXcXhVHYhC1R4nqoNV_EgFqZB4ns',
    appId: '1:1062422767346:android:3789e37fb5f7d5d137926b',
    messagingSenderId: '1062422767346',
    projectId: 'e-baladya-2026',
    storageBucket: 'e-baladya-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD7KpBmfNSPREPRLWNQBrYCaqYBv5CISQ',
    appId: '1:1062422767346:ios:a18a989a1310264337926b',
    messagingSenderId: '1062422767346',
    projectId: 'e-baladya-2026',
    storageBucket: 'e-baladya-2026.firebasestorage.app',
    iosBundleId: 'com.eBaladya.eBaladya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDD7KpBmfNSPREPRLWNQBrYCaqYBv5CISQ',
    appId: '1:1062422767346:ios:5b85592c89a3e76b37926b',
    messagingSenderId: '1062422767346',
    projectId: 'e-baladya-2026',
    storageBucket: 'e-baladya-2026.firebasestorage.app',
    iosBundleId: 'com.example.eBaladya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBF9up1vn2kwuGasjy7OuceF4t9qFSqq5o',
    appId: '1:1062422767346:web:f7737b9d30f7999637926b',
    messagingSenderId: '1062422767346',
    projectId: 'e-baladya-2026',
    authDomain: 'e-baladya-2026.firebaseapp.com',
    storageBucket: 'e-baladya-2026.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF9up1vn2kwuGasjy7OuceF4t9qFSqq5o',
    appId: '1:1062422767346:web:8a38e5e314b529ed37926b',
    messagingSenderId: '1062422767346',
    projectId: 'e-baladya-2026',
    authDomain: 'e-baladya-2026.firebaseapp.com',
    storageBucket: 'e-baladya-2026.firebasestorage.app',
  );

}